items:
- uid: System.Runtime.GCSettings
  commentId: T:System.Runtime.GCSettings
  id: GCSettings
  parent: System.Runtime
  children:
  - System.Runtime.GCSettings.IsServerGC
  - System.Runtime.GCSettings.LargeObjectHeapCompactionMode
  - System.Runtime.GCSettings.LatencyMode
  langs:
  - csharp
  - vb
  name: "XXX"
  fullName: System.Runtime.GCSettings
  type: Class
  source:
    remote:
      path: src/mscorlib/src/System/Runtime/GcSettings.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: GCSettings
    path: src/mscorlib/src/System/Runtime/GcSettings.cs
    startLine: 32
  assemblies:
  - System.Runtime
  namespace: System.Runtime
  summary: "\n<p>Specifies the garbage collection settings for the current process. </p>\n"
  syntax:
    content: public class GCSettings
    content.vb: Public Class GCSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
  nameWithType: GCSettings
- uid: System.Runtime.GCSettings.IsServerGC
  commentId: P:System.Runtime.GCSettings.IsServerGC
  id: IsServerGC
  parent: System.Runtime.GCSettings
  langs:
  - csharp
  - vb
  name: "XXX"
  fullName: System.Runtime.GCSettings.IsServerGC
  type: Property
  source:
    remote:
      path: src/mscorlib/src/System/Runtime/GcSettings.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: IsServerGC
    path: src/mscorlib/src/System/Runtime/GcSettings.cs
    startLine: 92
  assemblies:
  - System.Runtime
  namespace: System.Runtime
  summary: "\n<p>Gets a value that indicates whether server garbage collection is enabled.</p>\n"
  syntax:
    content: >-
      public static bool IsServerGC

      {
          [SecuritySafeCritical]
          get;
      }
    content.vb: Public Shared ReadOnly Property IsServerGC As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: "\n<p>\n<strong>true</strong> if server garbage collection is enabled; otherwise, <strong>false</strong>.</p>\n"
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
  nameWithType: GCSettings.IsServerGC
- uid: System.Runtime.GCSettings.LargeObjectHeapCompactionMode
  commentId: P:System.Runtime.GCSettings.LargeObjectHeapCompactionMode
  id: LargeObjectHeapCompactionMode
  parent: System.Runtime.GCSettings
  langs:
  - csharp
  - vb
  name: "XXX"
  fullName: System.Runtime.GCSettings.LargeObjectHeapCompactionMode
  type: Property
  source:
    remote:
      path: src/mscorlib/src/System/Runtime/GcSettings.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: LargeObjectHeapCompactionMode
    path: src/mscorlib/src/System/Runtime/GcSettings.cs
    startLine: 66
  assemblies:
  - System.Runtime
  namespace: System.Runtime
  summary: "\n<p>[Supported in the .NET Framework 4.5.1 and later versions] </p>\n<p>Gets or sets a value that indicates whether a full blocking garbage collection compacts the large object heap (LOH). </p>\n"
  syntax:
    content: >-
      public static GCLargeObjectHeapCompactionMode LargeObjectHeapCompactionMode

      {
          [SecuritySafeCritical]
          [ReliabilityContract(Consistency.WillNotCorruptState, Cer.Success)]
          get;
          [SecurityCritical]
          [HostProtection(MayLeakOnAbort = true)]
          [ReliabilityContract(Consistency.WillNotCorruptState, Cer.Success)]
          set;
      }
    content.vb: Public Shared Property LargeObjectHeapCompactionMode As GCLargeObjectHeapCompactionMode
    parameters: []
    return:
      type: System.Runtime.GCLargeObjectHeapCompactionMode
      description: "\n<p>One of the enumeration values that indicates whether a full blocking garbage collection compacts the LOH. </p>\n"
  seealso:
  - type: System.Runtime.GCLargeObjectHeapCompactionMode
    commentId: T:System.Runtime.GCLargeObjectHeapCompactionMode
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
  nameWithType: GCSettings.LargeObjectHeapCompactionMode
- uid: System.Runtime.GCSettings.LatencyMode
  commentId: P:System.Runtime.GCSettings.LatencyMode
  id: LatencyMode
  parent: System.Runtime.GCSettings
  langs:
  - csharp
  - vb
  name: "XXX"
  fullName: System.Runtime.GCSettings.LatencyMode
  type: Property
  source:
    remote:
      path: src/mscorlib/src/System/Runtime/GcSettings.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    id: LatencyMode
    path: src/mscorlib/src/System/Runtime/GcSettings.cs
    startLine: 40
  assemblies:
  - System.Runtime
  namespace: System.Runtime
  summary: "\n<p>Gets or sets the current latency mode for garbage collection.</p>\n"
  syntax:
    content: >-
      public static GCLatencyMode LatencyMode

      {
          [SecuritySafeCritical]
          [ReliabilityContract(Consistency.WillNotCorruptState, Cer.Success)]
          get;
          [SecurityCritical]
          [HostProtection(MayLeakOnAbort = true)]
          [ReliabilityContract(Consistency.WillNotCorruptState, Cer.Success)]
          set;
      }
    content.vb: Public Shared Property LatencyMode As GCLatencyMode
    parameters: []
    return:
      type: System.Runtime.GCLatencyMode
      description: "\n<p>One of the enumeration values that specifies the latency mode. </p>\n"
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "\n<p>The <xref href=\"System.Runtime.GCSettings.LatencyMode\" data-throw-if-not-resolved=\"false\"></xref> property is being set to an invalid value. </p>\n<p>-or-</p>\n<p>The <xref href=\"System.Runtime.GCSettings.LatencyMode\" data-throw-if-not-resolved=\"false\"></xref> property cannot be set to <xref href=\"System.Runtime.GCLatencyMode.NoGCRegion\" data-throw-if-not-resolved=\"false\"></xref>. </p>\n"
  see:
  - type: System.Security.SecurityCriticalAttribute
    commentId: T:System.Security.SecurityCriticalAttribute
  modifiers.csharp:
  - public
  - static
  - get
  - set
  modifiers.vb:
  - Public
  - Shared
  nameWithType: GCSettings.LatencyMode
references:
- uid: System.Runtime
  isExternal: false
  name: "XXX"
  fullName: System.Runtime
  nameWithType: System.Runtime
  commentId: N:System.Runtime
- uid: System.Object
  parent: System
  isExternal: false
  name: "XXX"
  fullName: System.Object
  nameWithType: Object
  commentId: T:System.Object
- uid: System.Object.ToString
  parent: System.Object
  isExternal: true
  name: "XXX"
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: "XXX"
    fullName: System.Object.ToString
    isExternal: true
  - name: "XXX"
    fullName: (
  - name: "XXX"
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: "XXX"
    fullName: System.Object.ToString
    isExternal: true
  - name: "XXX"
    fullName: (
  - name: "XXX"
    fullName: )
  nameWithType: Object.ToString()
  commentId: M:System.Object.ToString
- uid: System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: "XXX"
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: "XXX"
    fullName: System.Object.Equals
    isExternal: true
  - name: "XXX"
    fullName: (
  - uid: System.Object
    name: "XXX"
    fullName: System.Object
    isExternal: true
  - name: "XXX"
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: "XXX"
    fullName: System.Object.Equals
    isExternal: true
  - name: "XXX"
    fullName: (
  - uid: System.Object
    name: "XXX"
    fullName: System.Object
    isExternal: true
  - name: "XXX"
    fullName: )
  nameWithType: Object.Equals(Object)
  commentId: M:System.Object.Equals(System.Object)
- uid: System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: "XXX"
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: "XXX"
    fullName: System.Object.Equals
    isExternal: true
  - name: "XXX"
    fullName: (
  - uid: System.Object
    name: "XXX"
    fullName: System.Object
    isExternal: true
  - name: 'XXX '
    fullName: ', '
  - uid: System.Object
    name: "XXX"
    fullName: System.Object
    isExternal: true
  - name: "XXX"
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: "XXX"
    fullName: System.Object.Equals
    isExternal: true
  - name: "XXX"
    fullName: (
  - uid: System.Object
    name: "XXX"
    fullName: System.Object
    isExternal: true
  - name: 'XXX '
    fullName: ', '
  - uid: System.Object
    name: "XXX"
    fullName: System.Object
    isExternal: true
  - name: "XXX"
    fullName: )
  nameWithType: Object.Equals(Object, Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: "XXX"
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: "XXX"
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: "XXX"
    fullName: (
  - uid: System.Object
    name: "XXX"
    fullName: System.Object
    isExternal: true
  - name: 'XXX '
    fullName: ', '
  - uid: System.Object
    name: "XXX"
    fullName: System.Object
    isExternal: true
  - name: "XXX"
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: "XXX"
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: "XXX"
    fullName: (
  - uid: System.Object
    name: "XXX"
    fullName: System.Object
    isExternal: true
  - name: 'XXX '
    fullName: ', '
  - uid: System.Object
    name: "XXX"
    fullName: System.Object
    isExternal: true
  - name: "XXX"
    fullName: )
  nameWithType: Object.ReferenceEquals(Object, Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
- uid: System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: "XXX"
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: "XXX"
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: "XXX"
    fullName: (
  - name: "XXX"
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: "XXX"
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: "XXX"
    fullName: (
  - name: "XXX"
    fullName: )
  nameWithType: Object.GetHashCode()
  commentId: M:System.Object.GetHashCode
- uid: System.Object.GetType
  parent: System.Object
  isExternal: true
  name: "XXX"
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: "XXX"
    fullName: System.Object.GetType
    isExternal: true
  - name: "XXX"
    fullName: (
  - name: "XXX"
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: "XXX"
    fullName: System.Object.GetType
    isExternal: true
  - name: "XXX"
    fullName: (
  - name: "XXX"
    fullName: )
  nameWithType: Object.GetType()
  commentId: M:System.Object.GetType
- uid: System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: "XXX"
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: "XXX"
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: "XXX"
    fullName: (
  - name: "XXX"
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: "XXX"
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: "XXX"
    fullName: (
  - name: "XXX"
    fullName: )
  nameWithType: Object.MemberwiseClone()
  commentId: M:System.Object.MemberwiseClone
- uid: System
  isExternal: false
  name: "XXX"
  fullName: System
  nameWithType: System
  commentId: N:System
- uid: System.Boolean
  parent: System
  isExternal: false
  name: "XXX"
  fullName: System.Boolean
  nameWithType: Boolean
  commentId: T:System.Boolean
- uid: System.Runtime.GCLargeObjectHeapCompactionMode
  parent: System.Runtime
  isExternal: false
  name: "XXX"
  fullName: System.Runtime.GCLargeObjectHeapCompactionMode
  nameWithType: GCLargeObjectHeapCompactionMode
  commentId: T:System.Runtime.GCLargeObjectHeapCompactionMode
- uid: System.Runtime.GCLatencyMode
  parent: System.Runtime
  isExternal: false
  name: "XXX"
  fullName: System.Runtime.GCLatencyMode
  nameWithType: GCLatencyMode
  commentId: T:System.Runtime.GCLatencyMode
- uid: System.ArgumentOutOfRangeException
  isExternal: false
  name: "XXX"
  fullName: System.ArgumentOutOfRangeException
  nameWithType: ArgumentOutOfRangeException
  commentId: T:System.ArgumentOutOfRangeException
